channels:
    - pytorch
    - nvidia
    - conda-forge
name:
    torch-em
dependencies:
    - affogato
    - bioimageio.core >=0.5.0
    - napari
    - pycocotools
    - python-elf
    - pytorch
    - pytorch-cuda>=11.7  # you may need to change the pytorch version to match your system
    - tensorboard
    - tifffile
    - torchvision
    - tqdm
    - kornia
    - pip:
        - git+https://github.com/facebookresearch/segment-anything.git
        - git+https://github.com/constantinpape/torch-em.git
        - git+https://github.com/computational-cell-analytics/micro-sam.git
