channels:
    - conda-forge
name:
    dl-for-micro
dependencies:
    - bioimageio.core >=0.5.0
    - jupyter
    - napari
    - pyqt
    - pycocotools
    - python-elf
    - pytorch
    - tensorboard
    - tifffile
    - torchvision
    - torch_em
    - micro_sam
    - tqdm
